# Base configs
baseurl: "https://ghosh9691.github.io/prabal-ghosh-photography"
#baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "G-2GM4QVDX1G"

# UI configs
title: "Creations by Prabal Ghosh"
subtitle: "Your eyes, my lens!"
author: "Prabal Ghosh"
header:
 title: "Photographs"
 subtitle: "by Prabal Ghosh"
footer:
 name: "Hey there, I am Prabal!"
 bio: "I am a software developer by profession, a flight simulation enthusiast and an amateur photographer living in the NYC area."
# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "camera-retro"}, {"tag": "FNumber", "icon": "dot-circle-o"}, {"tag": "ExposureTime", "icon": "clock-o"}, {"tag": "ISOSpeedRatings", "icon": "info-circle"}]'
social_urls:
#  twitter: "https://www.twitter.com/ram__patra"
  instagram: "https://www.instagram.com/ghosh9691"
#  dribbble: "https://dribbble.com/rampatra"
  linkedin: "https://in.linkedin.com/in/prabalghosh"
  github: "https://www.github.com/ghosh9691"
  mail: "mailto:prabalg@gmail.com"
